

enum ZP_ERROR_e {
    ZP_ERROR_OK,
    ZP_ERROR_FAIL,
    ZP_ERROR_TIMEOUT,
    ZP_ERROR_BUSY,
    ZP_ERROR_INVALID_PARAM,
    ZP_ERROR_NULL_PTR,
    ZP_ERROR_UNSUPPORTED,
    ZP_ERROR_NOT_READY,
    ZP_ERROR_ALREADY_INITIALIZED,
    ZP_ERROR_OUT_OF_MEMORY,
    ZP_ERROR_RESOURCE_UNAVAILABLE,
    ZP_ERROR_CRC,
    ZP_ERROR_OVERFLOW,
    ZP_ERROR_PARSE
};